baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'TestTest'
theme = 'ananke'




Paginate = 3
googleAnalytics = ""
enableRobotsTXT = true



[params]
  text_color = "blue"
  author = "yyqq188"
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  background_color_class = "bg-black"
  recent_posts_number = 1




[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"